package app.enums;

public enum LanguageEnum {

    // Enum
    AFGHANISTAN("AF", "ps", "AF"),
    ALBANIA("AL", "sq", "AL"),
    ALGERIA("DZ", "ar", "DZ"),
    ANDORRA("AD", "ca", "AD"),
    ANGOLA("AO", "pt", "AO"),
    ANTIGUA_AND_BARBUDA("AG", "en", "AG"),
    ARGENTINA("AR", "es", "AR"),
    ARMENIA("AM", "hy", "AM"),
    AUSTRALIA("AU", "en", "AU"),
    AUSTRIA("AT", "de", "AT"),
    AZERBAIJAN("AZ", "az", "AZ"),
    BAHAMAS("BS", "en", "BS"),
    BAHRAIN("BH", "ar", "BH"),
    BANGLADESH("BD", "bn", "BD"),
    BARBADOS("BB", "en", "BB"),
    BELARUS("BY", "be", "BY"),
    BELGIUM("BE", "nl", "BE"),
    BELIZE("BZ", "en", "BZ"),
    BENIN("BJ", "fr", "BJ"),
    BHUTAN("BT", "dz", "BT"),
    BOLIVIA("BO", "es", "BO"),
    BOSNIA_AND_HERZEGOVINA("BA", "bs", "BA"),
    BOTSWANA("BW", "en", "BW"),
    BRAZIL("BR", "pt", "BR"),
    BRUNEI("BN", "ms", "BN"),
    BULGARIA("BG", "bg", "BG"),
    BURKINA_FASO("BF", "fr", "BF"),
    BURUNDI("BI", "fr", "BI"),
    CABO_VERDE("CV", "pt", "CV"),
    CAMBODIA("KH", "km", "KH"),
    CAMEROON("CM", "fr", "CM"),
    CANADA("CA", "en", "CA"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "fr", "CF"),
    CHAD("TD", "fr", "TD"),
    CHILE("CL", "es", "CL"),
    CHINA("CN", "zh", "CN"),
    COLOMBIA("CO", "es", "CO"),
    COMOROS("KM", "fr", "KM"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("CD", "fr", "CD"),
    REPUBLIC_OF_THE_CONGO("CG", "fr", "CG"),
    COSTA_RICA("CR", "es", "CR"),
    COTE_D_IVOIRE("CI", "fr", "CI"),
    CROATIA("HR", "hr", "HR"),
    CUBA("CU", "es", "CU"),
    CYPRUS("CY", "el", "CY"),
    CZECHIA("CZ", "cs", "CZ"),
    DENMARK("DK", "da", "DK"),
    DJIBOUTI("DJ", "fr", "DJ"),
    DOMINICA("DM", "en", "DM"),
    DOMINICAN_REPUBLIC("DO", "es", "DO"),
    ECUADOR("EC", "es", "EC"),
    EGYPT("EG", "ar", "EG"),
    EL_SALVADOR("SV", "es", "SV"),
    EQUATORIAL_GUINEA("GQ", "es", "GQ"),
    ERITREA("ER", "ti", "ER"),
    ESTONIA("EE", "et", "EE"),
    ESWATINI("SZ", "en", "SZ"),
    ETHIOPIA("ET", "am", "ET"),
    FIJI("FJ", "en", "FJ"),
    FINLAND("FI", "fi", "FI"),
    FRANCE("FR", "fr", "FR"),
    GABON("GA", "fr", "GA"),
    GAMBIA("GM", "en", "GM"),
    GEORGIA("GE", "ka", "GE"),
    GERMANY("DE", "de", "DE"),
    GHANA("GH", "en", "GH"),
    GREECE("GR", "el", "GR"),
    GRENADA("GD", "en", "GD"),
    GUATEMALA("GT", "es", "GT"),
    GUINEA("GN", "fr", "GN"),
    GUINEA_BISSAU("GW", "pt", "GW"),
    GUYANA("GY", "en", "GY"),
    HAITI("HT", "fr", "HT"),
    HOLY_SEE("VA", "la", "VA"),
    HONDURAS("HN", "es", "HN"),
    HUNGARY("HU", "hu", "HU"),
    ICELAND("IS", "is", "IS"),
    INDIA("IN", "hi", "IN"),
    INDONESIA("ID", "id", "ID"),
    IRAN("IR", "fa", "IR"),
    IRAQ("IQ", "ar", "IQ"),
    IRELAND("IE", "en", "IE"),
    ISRAEL("IL", "he", "IL"),
    ITALY("IT", "it", "IT"),
    JAMAICA("JM", "en", "JM"),
    JAPAN("JP", "ja", "JP"),
    JORDAN("JO", "ar", "JO"),
    KAZAKHSTAN("KZ", "kk", "KZ"),
    KENYA("KE", "sw", "KE"),
    KIRIBATI("KI", "en", "KI"),
    KUWAIT("KW", "ar", "KW"),
    KYRGYZSTAN("KG", "ky", "KG"),
    LAOS("LA", "lo", "LA"),
    LATVIA("LV", "lv", "LV"),
    LEBANON("LB", "ar", "LB"),
    LESOTHO("LS", "en", "LS"),
    LIBERIA("LR", "en", "LR"),
    LIBYA("LY", "ar", "LY"),
    LIECHTENSTEIN("LI", "de", "LI"),
    LITHUANIA("LT", "lt", "LT"),
    LUXEMBOURG("LU", "fr", "LU"),
    MADAGASCAR("MG", "mg", "MG"),
    MALAWI("MW", "en", "MW"),
    MALAYSIA("MY", "ms", "MY"),
    MALDIVES("MV", "dv", "MV"),
    MALI("ML", "fr", "ML"),
    MALTA("MT", "mt", "MT"),
    MARSHALL_ISLANDS("MH", "en", "MH"),
    MAURITANIA("MR", "ar", "MR"),
    MAURITIUS("MU", "en", "MU"),
    MEXICO("MX", "es", "MX"),
    MICRONESIA("FM", "en", "FM"),
    MOLDOVA("MD", "ro", "MD"),
    MONACO("MC", "fr", "MC"),
    MONGOLIA("MN", "mn", "MN"),
    MONTENEGRO("ME", "sr", "ME"),
    MOROCCO("MA", "ar", "MA"),
    MOZAMBIQUE("MZ", "pt", "MZ"),
    MYANMAR("MM", "my", "MM"),
    NAMIBIA("NA", "en", "NA"),
    NAURU("NR", "na", "NR"),
    NEPAL("NP", "ne", "NP"),
    NETHERLANDS("NL", "nl", "NL"),
    NEW_ZEALAND("NZ", "en", "NZ"),
    NICARAGUA("NI", "es", "NI"),
    NIGER("NE", "fr", "NE"),
    NIGERIA("NG", "en", "NG"),
    NORTH_KOREA("KP", "ko", "KP"),
    NORTH_MACEDONIA("MK", "mk", "MK"),
    NORWAY("NO", "no", "NO"),
    OMAN("OM", "ar", "OM"),
    PAKISTAN("PK", "ur", "PK"),
    PALAU("PW", "en", "PW"),
    STATE_OF_PALESTINE("PS", "ar", "PS"),
    PANAMA("PA", "es", "PA"),
    PAPUA_NEW_GUINEA("PG", "en", "PG"),
    PARAGUAY("PY", "es", "PY"),
    PERU("PE", "es", "PE"),
    PHILIPPINES("PH", "tl", "PH"),
    POLAND("PL", "pl", "PL"),
    PORTUGAL("PT", "pt", "PT"),
    QATAR("QA", "ar", "QA"),
    ROMANIA("RO", "ro", "RO"),
    RUSSIA("RU", "ru", "RU"),
    RWANDA("RW", "rw", "RW"),
    SAINT_KITTS_AND_NEVIS("KN", "en", "KN"),
    SAINT_LUCIA("LC", "en", "LC"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "en", "VC"),
    SAMOA("WS", "sm", "WS"),
    SAN_MARINO("SM", "it", "SM"),
    SAO_TOME_AND_PRINCIPE("ST", "pt", "ST"),
    SAUDI_ARABIA("SA", "ar", "SA"),
    SENEGAL("SN", "fr", "SN"),
    SERBIA("RS", "sr", "RS"),
    SEYCHELLES("SC", "en", "SC"),
    SIERRA_LEONE("SL", "en", "SL"),
    SINGAPORE("SG", "en", "SG"),
    SLOVAKIA("SK", "sk", "SK"),
    SLOVENIA("SI", "sl", "SI"),
    SOLOMON_ISLANDS("SB", "en", "SB"),
    SOMALIA("SO", "so", "SO"),
    SOUTH_AFRICA("ZA", "en", "ZA"),
    SOUTH_KOREA("KR", "ko", "KR"),
    SOUTH_SUDAN("SS", "en", "SS"),
    SPAIN("ES", "es", "ES"),
    SRI_LANKA("LK", "si", "LK"),
    SUDAN("SD", "ar", "SD"),
    SURINAME("SR", "nl", "SR"),
    SWEDEN("SE", "sv", "SE"),
    SWITZERLAND("CH", "de", "CH"),
    SYRIA("SY", "ar", "SY"),
    TAJIKISTAN("TJ", "tg", "TJ"),
    TANZANIA("TZ", "sw", "TZ"),
    THAILAND("TH", "th", "TH"),
    TIMOR_LESTE("TL", "pt", "TL"),
    TOGO("TG", "fr", "TG"),
    TONGA("TO", "to", "TO"),
    TRINIDAD_AND_TOBAGO("TT", "en", "TT"),
    TUNISIA("TN", "ar", "TN"),
    TURKEY("TR", "tr", "TR"),
    TURKMENISTAN("TM", "tk", "TM"),
    TUVALU("TV", "en", "TV"),
    UGANDA("UG", "en", "UG"),
    UKRAINE("UA", "uk", "UA"),
    UNITED_ARAB_EMIRATES("AE", "ar", "AE"),
    UNITED_KINGDOM("GB", "en", "GB"),
    UNITED_STATES("US", "en", "US"),
    URUGUAY("UY", "es", "UY"),
    UZBEKISTAN("UZ", "uz", "UZ"),
    VANUATU("VU", "bi", "VU"),
    VENEZUELA("VE", "es", "VE"),
    VIETNAM("VN", "vi", "VN"),
    YEMEN("YE", "ar", "YE"),
    ZAMBIA("ZM", "en", "ZM"),
    ZIMBABWE("ZW", "en", "ZW");

    // ____________________________________________________________________

    // Attributes
    private final String countryCode;
    private final String iso639;
    private final String iso3166;

    // ____________________________________________________________________

    LanguageEnum(String countryCode, String iso639, String iso3166) {
        this.countryCode = countryCode;
        this.iso639 = iso639;   //
        this.iso3166 = iso3166; // region
    }

    // ____________________________________________________________________

    public String getCountryCode() {
        return countryCode;
    }

    // ____________________________________________________________________

    public String getIso639() {
        return iso639;
    }

    // ____________________________________________________________________

    public String getIso3166() {
        return iso3166;
    }

    // ____________________________________________________________________

    public String getDisplayName() {
        return name().replace("_", " ");
    }

}